version: "3.9"

services:
  db:
    image: postgres:15
    container_name: sf_fire_db
    environment:
      POSTGRES_USER: fireuser
      POSTGRES_PASSWORD: firepass
      POSTGRES_DB: firedata
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_sf_fire
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "9091:80"
    depends_on:
      - db

volumes:
  pgdata:

